# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

readcpp <- function(path) {
    .Call(`_readthat_readcpp`, path)
}

readlcpp <- function(filename, first = 1L, last = 0L) {
    .Call(`_readthat_readlcpp`, filename, first, last)
}

