# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

readthiscpp <- function(url) {
    .Call(`_readthat_readthiscpp`, url)
}

rcpp_download_file <- function(url, out, verbose = TRUE) {
    .Call(`_readthat_rcpp_download_file`, url, out, verbose)
}

readthatcpp <- function(path) {
    .Call(`_readthat_readthatcpp`, path)
}

asyncpp <- function(urls) {
    .Call(`_readthat_asyncpp`, urls)
}

readthemcpp <- function(urls, outs) {
    .Call(`_readthat_readthemcpp`, urls, outs)
}

